### ISSUE TITLE
What versions of Python are supported?

### ISSUE THREAD

**Issue by cclauss** [pirate/security-growler#17]
Something in README.md could help contributors.

**Comment by pirate** [comment]
The python `Foundation` library that provides access to OS X API's like notification center is not available by default for python3.5, so for the moment only 2.7 is supported.

**Comment by pirate** [comment]
Added to the readme https://github.com/pirate/security-growler/commit/6ab8d0d7271451d4b028c2007a3f979d61d0e954.
