### ISSUE TITLE
sed: /Users/ in menu

### ISSUE THREAD

**Issue by TraderStf** [pirate/security-growler#23]
Hello,
I had SG, then I installed the SG-Light as I'm not in black mode.

When launched, I get this between the 2 lines
___
sed: /Users/trader/Library/Logs/SecurityGrowler.log
___

In fact, the update log is in /Users/trader/SecurityGrowler.log
and is updated.
Nothing in the /Logs folder.

After trying SG, then SGL, etc stopping the bg agent, SGL is ok and shows the ports list and the updated log is in the /Logs folder.

**Comment by pirate** [comment]
`/Users/trader/SecurityGrowler.log` is the old log location, neither SG nor SGL should be writing to this file as of version 2.1.

Can you confirm which version you are running?

**Comment by TraderStf** [comment]
2.2 downloaded from here on April 30.

**Comment by pirate** [comment]
Found the bug, the menubar app was only Quitting if the task name matched `Security Growler.app`, and wouldn't properly terminate `Security Growler Light.app`.  Fixed in https://github.com/pirate/security-growler/commit/8839a0ec7490eb213c8e30605e8fe23589bab1ca.

**Comment by pirate** [comment]
You can download the updated release here: https://github.com/pirate/security-growler/raw/master/Security%20Growler%20Light.app.zip
