### ISSUE TITLE
VPN triggers sudo lsof i:21 error

### ISSUE THREAD

**Issue by TraderStf** [pirate/security-growler#26]
sudo[123]: trader : no tty present and no askpass program specified ; TTY=unknown ; PWD=/Applications/Security Growler Light.app/Contents/Resources ; USER=root ; COMMAND=/usr/sbin/lsof +c 0 -i:21

Error msg repeated indefinitely, every 10-90 sec.

SGLight: v2.2 May, 2.
VPN PPTP
IP6 local only and IP6 off on router.

**Comment by pirate** [comment]
https://github.com/pirate/security-growler/issues/8
