### ISSUE TITLE
[Off-topic] What apps are there in your menu bar?

### ISSUE THREAD

**Issue by vincentcox** [pirate/security-growler#32]
Yes, this is very very offtopic, but my curiosity made me do it... 
Which apps are there in your menu-bar?
<img width="539" alt="687474703a2f2f7069726174652e6769746875622e696f2f73656375726974792d67726f776c65722f73637265656e73686f74732f6d656e756261725f322e504e47" src="https://cloud.githubusercontent.com/assets/9286611/15366548/21f9b14a-1d25-11e6-8204-a272fb00e2a2.png">

**Comment by JayBrown** [comment]
Standard menu bar: Bartender, AnyBar, Living Earth Desktop, Fantastical, iStat Menus (with date/time, battery, RAM, CPU, temperature/fanspeed, network up/down), OS X WiFi, Viscosity, gfxCardStatus, f.lux, Jettison, cmdQuit, MenuPrefs, ClipMenu, PopChar, Snaps, Remind Me, MUMenu, OS X Time Machine, iCloud Status, BackBlaze, LittleSnitch, BitBar with three instances

Bartender menu bar below the primary menu bar: OSX Notification Center, OS X Keyboard, OS X Spotlight, DefaultFolder, PopClip, HazeOver, MenuEclipse, SmartSleep, BlockBlock, SmartReporter, Micro Snitch, SecurityGrowler, Adguard, Owncloud, OS X Messages, Telegram, OS X Bluetooth, 1Password Mini, TranslateTab

Sometimes: Amphetamine, Cookie, Dropbox, ExpanDrive, LinkLiar, myXProtectStatus, NeoFinder, PopHub, Shady, Skype, Tranquility, StuffIt, Wunderlist, XProtectPluginChecker

:)

**Comment by vincentcox** [comment]
Thanks for the amazing and very extended app-list. This is golden to me!
(I actually googled "OS X WiFi app" before I realised it was just the icon you said...)

**Comment by JayBrown** [comment]
PS: there are at least two "Remind Me" apps out there… mine is the one by HighOrderBit… freeware, but only on the App Store. (Their website doesn't exist anymore, and it hasn't been updated since 2014.)

As a general note, there are always functionalities that you can program yourself and add to a BitBar plugin; e.g. I plan to migrate all the functions of cmdQuit to my BitBar system management plugin… maybe even Jettison (eject/mount volumes). It's not really important in terms of CPU, because they're idle anyway most of the time, but I need to free up some space. ;) 
![menubar](https://cloud.githubusercontent.com/assets/477431/15374642/8623953e-1d4b-11e6-81a5-3f2391f27d02.png)

**Comment by pirate** [comment]
I actually have a fairly minimal menubar right now, the only ones you see in that screenshot are:

 - iStat
 - Flux
 - Security Growler

I usually run Bitbar with a whole bunch of custom scripts (e.g. open pull request count, homebrew packages that need updates count).

I occasionally also use these menubar apps:

 - Micro Snitch (little snitch for camera and mic)
 - BlockBlock (notify on new startup items appearing)
 - 1Password
 - MacID (unlock mac with iPhone's touchid)
 - Lockdown (better mac lockscreen with alarms and notifications)
 - Sleepless (keeps macbook running with lid closed)
 - gfxCardStatus (only needed on older macs with dual GPUs)
 - Caffeine (keep mac awake)
 - ChitChat (Whatsapp client)
 - Bartender (menubar icon manager)
 - Karabiner (key re-mapper app)
 - BearededSpice (pause/skip youtube, soundcloud, etc. with keyboard media keys)
 - Boom (audio volume booster)
 - LineIn (audio passthrough app)
 - Soundflower (audio channel remapping tool)
 - Airfoil (better airplay controls)
 - AirServer (act as an airplay receiver)
 - Loading.app (network activity notifier)
 - Sip (color chooser)
 - Tunnelblick (openvpn client)
 - WifiSpoof (MAC address spoofer)

 
Other apps/tweaks you might find interesting:

 - mySIMBL
 - TotalFinder
 - TotalSpaces
 - TotalTerminal
 - HardwareGrowler (I should add this to the SG readme, it goes great with SG)
 - Moom (window manager)
 - PowerKey.app (remap your power key)
 - Sloth.app (show all open sockets)
 - TaskExplorer.app (program activity sampler)

**Comment by pirate** [comment]
@JayBrown running a Mac Pro with 16 cores there ;)?  What's the CPU/mem impact like with all those things running?

**Comment by JayBrown** [comment]
MBP mid-2010 (top i7 model), currently at 2%.

**Comment by pirate** [comment]
Wow, and I was thinking of selling my unused 2011 i7 MBP this year, I guess it's good for a quite a while longer.

**Comment by JayBrown** [comment]
Just wait until backupd, mds, CleanApp daemon etc. start working. ;)

**Comment by pirate** [comment]
Closing this as an issue, but please continue to contribute here! It's now linked to from the Readme: https://github.com/pirate/security-growler/commit/09a147b58fd83228b7db6060b29c992071c316fb.
