### ISSUE TITLE
Can't get past "Starting"

### ISSUE THREAD

**Issue by BenjaminHCCarr** [pirate/security-growler#34]
I have obviously looked over the code, and I assume I have an error in my setttings.py. But for some reason v2.2 isn't getting past "Starting ...." And the log is wholly unhelpful:

> [05/19 12:37] --------
> [05/19 13:10] --------
> [05/19 13:11] --------

[settings.py](https://github.com/pirate/security-growler/files/273075/settings.txt)

[SecurityGrowler.log](https://github.com/pirate/security-growler/files/273077/SecurityGrowler.txt)

**Comment by pirate** [comment]
I should make the logging better for failed imports.  I think you don't have `gntp` installed so the `growl` logger is failing to import on start.

What's the output of running this in terminal: `cd /Applications/Security\ Growler.app/Contents/Resources/; python -m loggers.growl`?

**Comment by BenjaminHCCarr** [comment]
I'll run that LATE tonight. I have growler plus cli growler installed. It had been working for days, that's why I added it to HomeBrew, I loved it. But then either an edit to the settings file or something random messed it up. I did do a OSX Security patch on 10.10.5 this week. Also I don't remember how you are calling python, are you calling python, python2, or python3? I think I may have had to symlink to make it work, and a sec. update may have broken that.

**Comment by BenjaminHCCarr** [comment]
Bah, I blew away my config testing a homebrew thing and it is happily plugging along, I probably had a python space error/tab/quote error, would be nice to monitor the Apple Server ports though, I'll look into it again, especially as the config is above.

But in the truest words of closing something "it's not you, it's me" it was in the config file somewhere.
