### ISSUE TITLE
Immediately Stopped Working After Launch

### ISSUE THREAD

**Issue by faxotherapy** [pirate/security-growler#35]
Hello,
I've got this message on my notification panel: `Stopped Watching Sources @ 14:20 IOError` Do I need to do a further tweak in order to make it run on my OS 10.11.3?
Thanks.
Faxo

**Comment by pirate** [comment]
Can you download the most recent version with full error logging from [here](https://github.com/pirate/security-growler/raw/master/Security%20Growler.app.zip), and then paste the output you get after launching it.

Make sure to click 'Stop the Background Agent & Quit' before running the new version.

**Comment by faxotherapy** [comment]
Thanks for your reply.

1. I was running the latest version. I should have mentioned it; sorry. However, I have reinstalled from your ZIP file with no difference in terms of result.

2. I must point out that I run the app under regular session. I haven't been asked for any higher privileged access.
3. Here's the log file as asked:

 		[05/23 19:09] Stopped Watching Sources: IOError: Traceback (most recent call last):
  		File "/Users/Nathalie/Downloads/Security Growler.app/Contents/Resources/growler.py", line 41, in <module> 
  		  watch_sources()
  		File "/Users/Nathalie/Downloads/Security Growler.app/Contents/Resources/growler.py", line 18, in watch_sources
    	  for source, line in get_new_lines():
  		File "/Users/Nathalie/Downloads/Security Growler.app/Contents/Resources/sources/__init__.py", line 19, in get_new_lines
    	  next_line = next(generator)
  		File "/Users/Nathalie/Downloads/Security Growler.app/Contents/Resources/sources/logfile.py", line 7, in gen_lines
    	  with open(path, 'r') as logfile:
		IOError: [Errno 13] Permission denied: '/var/log/system.log'
		
For now, graphical results are as follows:
![starting](https://cloud.githubusercontent.com/assets/6538008/15480314/d669bada-211c-11e6-982f-bee4fcb114e4.jpg)

![message](https://cloud.githubusercontent.com/assets/6538008/15480338/f260a08c-211c-11e6-9e4b-23a4293ab8b5.jpg)

The first snapshot shows that the app constantly remains in the status `Starting…`

**Comment by pirate** [comment]
You cannot run the app under a non-admin account, this is expected behavior, although I guess I could make the error message more informative.

**Comment by pirate** [comment]
Updated the docs: https://github.com/pirate/security-growler/commit/ef4c552545db62376df5a5fbd1943d29e1da274d

**Comment by timeartist** [comment]
To anyone who's having this issue and really doesn't want to run with a admin account, you can add the user to the wheel group `sudo dseditgroup -o edit -a $username_to_add -t user wheel` and `chmod 644 /var/log/system.log`  - Still doesn't give your user the ability to sudo, but allows the growler to work

**Comment by pirate** [comment]
@timeartist careful, that effectively makes your user part of the admin group, and gives them admin read permissions to a lot of things in the filesystem.  I don't recommend adding yourself to wheel just to run this app, as it defeats the purpose of running a non-admin account in the first place.  The `sudo chmod 644 /var/log/system.log` should be enough on it's own to allow your non-admin account read access.

**Comment by timeartist** [comment]
I noticed that later as well. Thanks for the info
