### ISSUE TITLE
Airport state change

### ISSUE THREAD

**Issue by flemingm** [pirate/security-growler#40]
System Log contains events for Airport Wi-Fi

OS X 10.11.6:

kernel[0]: AirPort: Link Up on en0
kernel[0]: AirPort: RSN handshake complete on en0

kernel[0]: AirPort: Link Down on en0. Reason 8 (Disassociated because station leaving).

Possible Parser:
```
import re

# Should we filter on: kernel[0]: AirPort: 

SUDO_EVENT_FILTER = re.compile('kernel')

#Nov 14 20:29:24 Mark Fleming
# kernel[0]: AirPort: Link Up on en0
# kernel[0]: AirPort: RSN handshake complete on en0
# 
# kernel[0]: AirPort: Link Down on en0. Reason 8 (Disassociated because station leaving).


TITLE = 'AIRPORT EVENT: {interface}'
BODY = '{port}\n'

EXCLUDE_LINES = ('airportd',)  # dont alert on sudo events that contain these strings


def parse(line, source=None):
    if SUDO_EVENT_FILTER.findall(line) and not any(pattern in line for pattern in EXCLUDE_LINES):
        interface = line.split('Link Up on ', 1)[-1]
        port = line.split('AirPort:', 1)[-1]
       
        return ('alert',
            TITLE.format(interface=interface),
            BODY.format(port=port))

    return (None, '', '')
```

**Comment by pirate** [comment]
I recommend using [Hardware Growler](https://www.macupdate.com/app/mac/40750/hardwaregrowler) or [Meta Growler](http://download.freedownloadmanager.org/Mac-OS/MetaGrowler/FREE-0.5.2.html).  I use both, and aim to have as little overlap with them as possible, as they are great applications that do the job well already.

![screen shot 2016-12-17 at 12 27 12 am](https://cloud.githubusercontent.com/assets/511499/21284665/53d0b7e6-c3f0-11e6-9322-de99ab4b1797.PNG)
Hardware Growler
