### ISSUE TITLE
iTunes 3689

### ISSUE THREAD

**Issue by SainteCelery** [pirate/security-growler#44]
Is it normal for iTunes to be making incessant port connections when home sharing is turned on but not (knowingly) being used?

**Comment by pirate** [comment]
How big is your network, do you have office coworker who might be accidentally connecting?

**Comment by SainteCelery** [comment]
Hi. This is on my home network. Just the cat here.

**Comment by pirate** [comment]
I'm sure your cat is just a music aficionado, and secretly streams your library :)
Can you confirm that the status is "On, no users connected" after you notice one of the alerts?
<img width="682" alt="screen shot 2017-02-21 at 2 19 20 pm" src="https://cloud.githubusercontent.com/assets/511499/23180844/ccc59584-f840-11e6-8c44-780401a86dde.PNG">
(iTunes Preferences^)
