### ISSUE TITLE
Autostart or Persistence 

### ISSUE THREAD

**Issue by ajinabraham** [pirate/security-growler#46]
Growler get killed or doesn't have an autostart option. Everytime I have to run it manually.

**Comment by moha19** [comment]
Hi,
In mobsf dynamic analysis. Would it start virtual box as multi user from multi request?

**Comment by ajinabraham** [comment]
@moha19 This is security-growler repository. Please ask mobsf related questions in corresponding repository.

**Comment by ajinabraham** [comment]
Closing this as I found a similar thread here: https://github.com/pirate/security-growler/issues/39
