### ISSUE TITLE
All menus disabled

### ISSUE THREAD

**Issue by TraderStf** [pirate/security-growler#9]
Hello,

Running but all menu except Quit are disabled.
Each I launch SG, got this in Console.
I cut "25/04/16 18:16:2" from each line.

<pre>
1,700 lsd[414]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
1,725 launchservicesd[80]: SecTaskLoadEntitlements failed error=22
1,729 launchservicesd[80]: SecTaskLoadEntitlements failed error=22
1,750 webinspectord[1355]: SecTaskLoadEntitlements failed error=22
1,750 webinspectord[1355]: SecTaskLoadEntitlements failed error=22
1,814 appleeventsd[51]: SecTaskLoadEntitlements failed error=22
1,829 usernoted[434]: SecTaskLoadEntitlements failed error=22
4,730 Barsoom[561]: 27700 already launched. Inject
4,796 Security Growler[27700]: barsoomHelper loaded
4,902 launchservicesd[80]: SecTaskLoadEntitlements failed error=22
6,755 launchservicesd[80]: SecTaskLoadEntitlements failed error=22
</pre>

**Comment by pirate** [comment]
I need three pieces of info to debug further:

1. What Mac OS X version are you running?
2. What's the output of running `sh /Applications/Security\ Growler.app/Contents/Resources/script` in Terminal?
3. Does running `sh /Applications/Security\ Growler.app/Contents/Resources/script "About Security Growler"` in terminal open a new tab in your browser with the Security Growler website?

Thanks for reporting!

**Comment by TraderStf** [comment]
10.11.4 (15E65)

<pre>
            🍺 Security Growler is running. 🍺
Settings...
View the full log...
Stop the background agent...
—————————————————————————————————————————————————————————
[04/25 17:48] Started Watching Sources: 
/var/log/system.log      : for sudo,ssh,portscan events
port 3689                : for connections events
port 3306                : for connections events
port 5900                : for vnc events
port 21                  : for connections events
port 585                 : for connections events
port 5432                : for connections events
port 445                 : for connections events
—————————————————————————————————————————————————————————
Request a Feature
About Security Growler
</pre>

A new page in fact, yes.


FYI, I have a lot of 'security' all objective-see, bitdefender, various vpn, littlesnitch, what else... batman

thanks,

**Comment by pirate** [comment]
Interesting, it seems to be a bug with the Platypus menubar system then, not the script itself handling click events.

If you have a few minutes, could you try:

1. Download the [Platypus App](http://sveinbjorn.org/platypus)
2. clone this repo
3. open [Security Growler.platypus](https://github.com/pirate/security-growler/blob/master/Security%20Growler.platypus) in Platypus
4. create a new development version of the app
5. run the dev version and see if the menubar items work


![screen shot 2016-04-25 at 1 35 13 pm](https://cloud.githubusercontent.com/assets/511499/14794620/a79b0aa8-0aea-11e6-8288-aa203543f140.PNG)

**Comment by TraderStf** [comment]
As I saw all the menu, but Quit, in grey I did not try but they are working.
When the pointer is over, it becomes a little bit lighter.
I am using white menu bar, graphite appearance.

May I suggest to remove the 2 beer icons... Square head clients will not like this...

**Comment by TraderStf** [comment]
Platypus 5.1 was already installed, I have a folder inside Applications folder.
I test it few weeks ago.

Will try asap.

**Comment by TraderStf** [comment]
Which Font are you using in the Finder (left/lateral bar)?

**Comment by pirate** [comment]
Ah, I designed this for Mac in Dark Mode, clearly I should tweak the color scheme a little so that it works for both light and dark.

The font I'm using is http://input.fontbureau.com/systemfont/

**Comment by pirate** [comment]
https://github.com/pirate/security-growler/issues/11
